spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_orders_db?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8084

# JWT secret (read from env JWT_SECRET or fallback to the user-service default)
jwt:
  secret: ${JWT_SECRET:Ue7d9Kj4QpLmZ8sR2xvTgH5yVbNc1fR0wYz3AaPqS6tHjK9L}

# Microservice endpoints
microservices:
  product-service:
    url: http://localhost:8083
