-- Crear la base de datos si no existe
DROP DATABASE IF EXISTS ecommerce_products;
CREATE DATABASE IF NOT EXISTS ecommerce_products;
USE ecommerce_products;

-- Crear la tabla products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0.01),
    stock INT NOT NULL CHECK (stock >= 0),
    category VARCHAR(50) NOT NULL,
    image_url VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO products (name, description, price, stock, category, image_url, active, created_at, updated_at)
VALUES ('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI.', 19.99, 150, 'Electronics',
        'https://dummyimage.com/200x200/000/fff&text=Mouse', true, NOW(), NOW()),
       ('Bluetooth Headphones', 'Over-ear headphones with noise cancellation.', 59.99, 80, 'Electronics',
        'https://dummyimage.com/200x200/000/fff&text=Headphones', true, NOW(), NOW()),
       ('Gaming Keyboard', 'Mechanical keyboard with RGB lighting.', 49.99, 60, 'Electronics',
        'https://dummyimage.com/200x200/000/fff&text=Keyboard', true, NOW(), NOW()),
       ('Smart Watch', 'Fitness tracker with heart rate monitor.', 89.99, 40, 'Wearables',
        'https://dummyimage.com/200x200/000/fff&text=Watch', true, NOW(), NOW()),
       ('USB-C Charger', 'Fast charging USB-C wall adapter.', 14.99, 200, 'Accessories',
        'https://dummyimage.com/200x200/000/fff&text=Charger', true, NOW(), NOW()),
       ('Laptop Stand', 'Adjustable aluminum laptop stand.', 29.99, 120, 'Accessories',
        'https://dummyimage.com/200x200/000/fff&text=Stand', true, NOW(), NOW()),
       ('External SSD', 'Portable 1TB external SSD drive.', 109.99, 35, 'Storage',
        'https://dummyimage.com/200x200/000/fff&text=SSD', true, NOW(), NOW()),
       ('4K Monitor', '27-inch 4K UHD monitor with HDR.', 299.99, 25, 'Electronics',
        'https://dummyimage.com/200x200/000/fff&text=Monitor', true, NOW(), NOW()),
       ('Wireless Earbuds', 'Compact earbuds with charging case.', 39.99, 90, 'Wearables',
        'https://dummyimage.com/200x200/000/fff&text=Earbuds', true, NOW(), NOW()),
       ('Smartphone Case', 'Shockproof case for latest smartphones.', 12.99, 300, 'Accessories',
        'https://dummyimage.com/200x200/000/fff&text=Case', true, NOW(), NOW()),
       ('Fitness Band', 'Waterproof fitness band with sleep tracking.', 24.99, 110, 'Wearables',
        'https://dummyimage.com/200x200/000/fff&text=Band', true, NOW(), NOW()),
       ('Portable Speaker', 'Bluetooth speaker with deep bass.', 34.99, 70, 'Electronics',
        'https://dummyimage.com/200x200/000/fff&text=Speaker', true, NOW(), NOW()),
       ('Action Camera', '4K action camera with waterproof case.', 79.99, 45, 'Cameras',
        'https://dummyimage.com/200x200/000/fff&text=Camera', true, NOW(), NOW()),
       ('Tripod Stand', 'Lightweight tripod for cameras and phones.', 22.99, 85, 'Accessories',
        'https://dummyimage.com/200x200/000/fff&text=Tripod', true, NOW(), NOW()),
       ('LED Desk Lamp', 'Dimmable LED lamp with USB charging port.', 18.99, 130, 'Home',
        'https://dummyimage.com/200x200/000/fff&text=Lamp', true, NOW(), NOW()),
       ('Smart Thermostat', 'WiFi-enabled smart home thermostat.', 129.99, 20, 'Home',
        'https://dummyimage.com/200x200/000/fff&text=Thermostat', true, NOW(), NOW()),
       ('Robot Vacuum', 'Automatic robot vacuum cleaner.', 199.99, 15, 'Home',
        'https://dummyimage.com/200x200/000/fff&text=Vacuum', true, NOW(), NOW()),
       ('Electric Toothbrush', 'Rechargeable electric toothbrush.', 29.99, 100, 'Personal Care',
        'https://dummyimage.com/200x200/000/fff&text=Toothbrush', true, NOW(), NOW()),
       ('Hair Dryer', 'Ionic hair dryer with cool shot.', 27.99, 60, 'Personal Care',
        'https://dummyimage.com/200x200/000/fff&text=Dryer', true, NOW(), NOW()),
       ('Espresso Machine', 'Automatic espresso coffee machine.', 149.99, 18, 'Kitchen',
        'https://dummyimage.com/200x200/000/fff&text=Espresso', true, NOW(), NOW()),
       ('Air Fryer', 'Digital air fryer with 6 presets.', 79.99, 30, 'Kitchen',
        'https://dummyimage.com/200x200/000/fff&text=AirFryer', true, NOW(), NOW()),
       ('Blender', 'High-speed blender for smoothies.', 44.99, 50, 'Kitchen',
        'https://dummyimage.com/200x200/000/fff&text=Blender', true, NOW(), NOW()),
       ('Yoga Mat', 'Non-slip yoga mat for exercise.', 15.99, 140, 'Sports',
        'https://dummyimage.com/200x200/000/fff&text=YogaMat', true, NOW(), NOW()),
       ('Dumbbell Set', 'Adjustable dumbbell set for home gym.', 59.99, 25, 'Sports',
        'https://dummyimage.com/200x200/000/fff&text=Dumbbells', true, NOW(), NOW()),
       ('Tennis Racket', 'Lightweight graphite tennis racket.', 34.99, 35, 'Sports',
        'https://dummyimage.com/200x200/000/fff&text=Racket', true, NOW(), NOW()),
       ('Camping Tent', '4-person waterproof camping tent.', 89.99, 12, 'Outdoors',
        'https://dummyimage.com/200x200/000/fff&text=Tent', true, NOW(), NOW()),
       ('Hiking Backpack', '50L hiking backpack with rain cover.', 54.99, 22, 'Outdoors',
        'https://dummyimage.com/200x200/000/fff&text=Backpack', true, NOW(), NOW()),
       ('Sleeping Bag', '3-season sleeping bag for camping.', 39.99, 28, 'Outdoors',
        'https://dummyimage.com/200x200/000/fff&text=SleepingBag', true, NOW(), NOW()),
       ('Desk Organizer', 'Multi-compartment desk organizer.', 11.99, 160, 'Office',
        'https://dummyimage.com/200x200/000/fff&text=Organizer', true, NOW(), NOW()),
       ('Notebook Set', 'Set of 5 ruled notebooks.', 9.99, 210, 'Office',
        'https://dummyimage.com/200x200/000/fff&text=Notebooks', true, NOW(), NOW()),
       ('Ballpoint Pens', 'Pack of 20 smooth ballpoint pens.', 6.99, 250, 'Office',
        'https://dummyimage.com/200x200/000/fff&text=Pens', true, NOW(), NOW());
